classes/image.bbclass: Fix it when WRTEMPLATE_CONF_WRIMAGE is not defined.
Issue: LIN9-8185

Fixed when update layer index:
$ ./update.py -b WRLINUX_9_BASE -l wr-base
INFO: Collecting data for layer wr-base on branch WRLINUX_9_LTS_CVE_RCPL0021
ERROR: Unable to read /path/to/images/wrlinux-image-glibc-std.bb: ParseError in ${@['${WRTEMPLATE_CONF_WRIMAGE}', 'wrlnoimage.inc'][d.getVar('WRTEMPLATE_IMAGE', True) != '1']}: not a BitBake file

These vars are defined in conf/bitbake.conf, but this bitbake.conf is not used
when update.py runs, so use a neat way to fix the problem.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>